# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/gephery/github/code-name

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/gephery/github/code-name

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.8.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/gephery/github/code-name/CMakeFiles /users/gephery/github/code-name/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/gephery/github/code-name/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code_name

# Build rule for target.
code_name: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 code_name
.PHONY : code_name

# fast build rule for target.
code_name/fast:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/build
.PHONY : code_name/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/main.cpp.s
.PHONY : main.cpp.s

src/graphics/sprite.o: src/graphics/sprite.cpp.o

.PHONY : src/graphics/sprite.o

# target to build an object file
src/graphics/sprite.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/graphics/sprite.cpp.o
.PHONY : src/graphics/sprite.cpp.o

src/graphics/sprite.i: src/graphics/sprite.cpp.i

.PHONY : src/graphics/sprite.i

# target to preprocess a source file
src/graphics/sprite.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/graphics/sprite.cpp.i
.PHONY : src/graphics/sprite.cpp.i

src/graphics/sprite.s: src/graphics/sprite.cpp.s

.PHONY : src/graphics/sprite.s

# target to generate assembly for a file
src/graphics/sprite.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/graphics/sprite.cpp.s
.PHONY : src/graphics/sprite.cpp.s

src/graphics/sprite_back.o: src/graphics/sprite_back.cpp.o

.PHONY : src/graphics/sprite_back.o

# target to build an object file
src/graphics/sprite_back.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/graphics/sprite_back.cpp.o
.PHONY : src/graphics/sprite_back.cpp.o

src/graphics/sprite_back.i: src/graphics/sprite_back.cpp.i

.PHONY : src/graphics/sprite_back.i

# target to preprocess a source file
src/graphics/sprite_back.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/graphics/sprite_back.cpp.i
.PHONY : src/graphics/sprite_back.cpp.i

src/graphics/sprite_back.s: src/graphics/sprite_back.cpp.s

.PHONY : src/graphics/sprite_back.s

# target to generate assembly for a file
src/graphics/sprite_back.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/graphics/sprite_back.cpp.s
.PHONY : src/graphics/sprite_back.cpp.s

src/items/item.o: src/items/item.cpp.o

.PHONY : src/items/item.o

# target to build an object file
src/items/item.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/items/item.cpp.o
.PHONY : src/items/item.cpp.o

src/items/item.i: src/items/item.cpp.i

.PHONY : src/items/item.i

# target to preprocess a source file
src/items/item.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/items/item.cpp.i
.PHONY : src/items/item.cpp.i

src/items/item.s: src/items/item.cpp.s

.PHONY : src/items/item.s

# target to generate assembly for a file
src/items/item.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/items/item.cpp.s
.PHONY : src/items/item.cpp.s

src/mob/mob.o: src/mob/mob.cpp.o

.PHONY : src/mob/mob.o

# target to build an object file
src/mob/mob.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/mob/mob.cpp.o
.PHONY : src/mob/mob.cpp.o

src/mob/mob.i: src/mob/mob.cpp.i

.PHONY : src/mob/mob.i

# target to preprocess a source file
src/mob/mob.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/mob/mob.cpp.i
.PHONY : src/mob/mob.cpp.i

src/mob/mob.s: src/mob/mob.cpp.s

.PHONY : src/mob/mob.s

# target to generate assembly for a file
src/mob/mob.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/mob/mob.cpp.s
.PHONY : src/mob/mob.cpp.s

src/mob/mob_manager.o: src/mob/mob_manager.cpp.o

.PHONY : src/mob/mob_manager.o

# target to build an object file
src/mob/mob_manager.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/mob/mob_manager.cpp.o
.PHONY : src/mob/mob_manager.cpp.o

src/mob/mob_manager.i: src/mob/mob_manager.cpp.i

.PHONY : src/mob/mob_manager.i

# target to preprocess a source file
src/mob/mob_manager.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/mob/mob_manager.cpp.i
.PHONY : src/mob/mob_manager.cpp.i

src/mob/mob_manager.s: src/mob/mob_manager.cpp.s

.PHONY : src/mob/mob_manager.s

# target to generate assembly for a file
src/mob/mob_manager.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/mob/mob_manager.cpp.s
.PHONY : src/mob/mob_manager.cpp.s

src/windowing/fonter.o: src/windowing/fonter.cpp.o

.PHONY : src/windowing/fonter.o

# target to build an object file
src/windowing/fonter.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/fonter.cpp.o
.PHONY : src/windowing/fonter.cpp.o

src/windowing/fonter.i: src/windowing/fonter.cpp.i

.PHONY : src/windowing/fonter.i

# target to preprocess a source file
src/windowing/fonter.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/fonter.cpp.i
.PHONY : src/windowing/fonter.cpp.i

src/windowing/fonter.s: src/windowing/fonter.cpp.s

.PHONY : src/windowing/fonter.s

# target to generate assembly for a file
src/windowing/fonter.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/fonter.cpp.s
.PHONY : src/windowing/fonter.cpp.s

src/windowing/game_winda.o: src/windowing/game_winda.cpp.o

.PHONY : src/windowing/game_winda.o

# target to build an object file
src/windowing/game_winda.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/game_winda.cpp.o
.PHONY : src/windowing/game_winda.cpp.o

src/windowing/game_winda.i: src/windowing/game_winda.cpp.i

.PHONY : src/windowing/game_winda.i

# target to preprocess a source file
src/windowing/game_winda.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/game_winda.cpp.i
.PHONY : src/windowing/game_winda.cpp.i

src/windowing/game_winda.s: src/windowing/game_winda.cpp.s

.PHONY : src/windowing/game_winda.s

# target to generate assembly for a file
src/windowing/game_winda.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/game_winda.cpp.s
.PHONY : src/windowing/game_winda.cpp.s

src/windowing/winda_box.o: src/windowing/winda_box.cpp.o

.PHONY : src/windowing/winda_box.o

# target to build an object file
src/windowing/winda_box.cpp.o:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/winda_box.cpp.o
.PHONY : src/windowing/winda_box.cpp.o

src/windowing/winda_box.i: src/windowing/winda_box.cpp.i

.PHONY : src/windowing/winda_box.i

# target to preprocess a source file
src/windowing/winda_box.cpp.i:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/winda_box.cpp.i
.PHONY : src/windowing/winda_box.cpp.i

src/windowing/winda_box.s: src/windowing/winda_box.cpp.s

.PHONY : src/windowing/winda_box.s

# target to generate assembly for a file
src/windowing/winda_box.cpp.s:
	$(MAKE) -f CMakeFiles/code_name.dir/build.make CMakeFiles/code_name.dir/src/windowing/winda_box.cpp.s
.PHONY : src/windowing/winda_box.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... code_name"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/graphics/sprite.o"
	@echo "... src/graphics/sprite.i"
	@echo "... src/graphics/sprite.s"
	@echo "... src/graphics/sprite_back.o"
	@echo "... src/graphics/sprite_back.i"
	@echo "... src/graphics/sprite_back.s"
	@echo "... src/items/item.o"
	@echo "... src/items/item.i"
	@echo "... src/items/item.s"
	@echo "... src/mob/mob.o"
	@echo "... src/mob/mob.i"
	@echo "... src/mob/mob.s"
	@echo "... src/mob/mob_manager.o"
	@echo "... src/mob/mob_manager.i"
	@echo "... src/mob/mob_manager.s"
	@echo "... src/windowing/fonter.o"
	@echo "... src/windowing/fonter.i"
	@echo "... src/windowing/fonter.s"
	@echo "... src/windowing/game_winda.o"
	@echo "... src/windowing/game_winda.i"
	@echo "... src/windowing/game_winda.s"
	@echo "... src/windowing/winda_box.o"
	@echo "... src/windowing/winda_box.i"
	@echo "... src/windowing/winda_box.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

